import React, { useState, useEffect } from 'react';
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';
import './App.css';
import DataFetcher from './components/DataFetcher';
import OceanVisualization from './components/OceanVisualization';
import NavBar from './components/NavBar';

// Define the OceanData type
type OceanData = {
  time: string;
  tide: number;
  temperature: number;
  salinity: number;
  waveHeight: number;
  currentSpeed: number;
};

const App: React.FC = () => {
  const [oceanData, setOceanData] = useState<OceanData[]>([]);

  useEffect(() => {
    const interval = setInterval(() => {
      const newData: OceanData = {
        time: new Date().toLocaleTimeString(),
        tide: parseFloat((Math.random() * 5).toFixed(2)),
        temperature: parseFloat((Math.random() * 30 + 10).toFixed(2)),
        salinity: parseFloat((Math.random() * 10 + 30).toFixed(2)),
        waveHeight: parseFloat((Math.random() * 3).toFixed(2)),
        currentSpeed: parseFloat((Math.random() * 2).toFixed(2)),
      };

      setOceanData((prev) => [...prev.slice(-19), newData]);
    }, 5000);

    return () => clearInterval(interval);
  }, []);

  return (
    <Router>
      <div className="App">
        <NavBar />
        <Routes>
          <Route path="/" element={
            <>
              <h1 className="title">🌊 OceanEye: Real-time Oceanography Dashboard</h1>
              <p>Welcome to OceanEye! Your real-time source for oceanographic data and research.</p>
            </>
          } />
          <Route path="/research" element={
            <>
              <h1 className="title">Research</h1>
              <OceanVisualization data={oceanData} />
            </>
          } />
          <Route path="/learn" element={
            <>
              <h1 className="title">Learn About Oceans</h1>
              <div>
                <h2>Oceans</h2>
                <p>Oceans are vast bodies of saltwater that cover more than 70% of the Earth's surface. They are critical for regulating climate, supporting marine life, and providing food and oxygen.</p>
                <h2>Corals</h2>
                <p>Corals are marine invertebrates that form colonies and build the reefs that support diverse marine ecosystems.</p>
                <h2>Tides</h2>
                <p>Tides are the periodic rise and fall of sea levels caused by the gravitational forces of the moon and the sun.</p>
                <h2>Waves</h2>
                <p>Waves are disturbances on the surface of oceans, generated by wind, underwater earthquakes, or gravitational forces.</p>
              </div>
            </>
          } />
          <Route path="/analysis" element={
            <>
              <h1 className="title">Analysis</h1>
              <p>Advanced analysis tools to forecast ocean trends and patterns. Machine learning and statistical models will be used here in future versions.</p>
            </>
          } />
        </Routes>
      </div>
    </Router>
  );
};

export default App;
